# Generated by Django 5.2.1 on 2025-05-18 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnh', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.TextField()),
                ('destino', models.TextField()),
                ('distancia', models.FloatField(default=0)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('motorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.motorista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
