version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: bash -c "source venv/bin/activate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    image: nginx
    ports:
      - "5173:80"
    volumes:
      - ./frontend_vite/dist:/usr/share/nginx/html
    restart: always

volumes:
  backend_data:
  frontend_dist:
